---
apiVersion: v1
kind: Namespace
metadata:
  name:  external-name-svc-app

---
apiVersion: v1
kind: Service
metadata:
  name: external-name-svc-app
  namespace: external-name-svc-app
spec:
  type: ExternalName
  externalName: google.com
